version: '3'

services:

  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=cep'
      - 'MONGO_INITDB_ROOT_PASSWORD=cep123'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    #volumes:
    #  - mongodb_data:/data/db

  mongodblogs:
    image: 'mongo:latest'
    container_name: mongodblogs
    environment:
      - 'MONGO_INITDB_DATABASE=logs'
      - 'MONGO_INITDB_ROOT_PASSWORD=log123'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
    #volumes:
    #  - mongodblogs_data:/data/db

  wiremock_zipcode:
    image:  wiremock/wiremock:3.10.0
    container_name: zipcode
    volumes:
      - .wiremock/zipcode/__files:/home/wiremock/__files
      - .wiremock/zipcode/mappings:/home/wiremock/mappings
    ports:
      - 8082:8080

  wiremock_establishment:
    image: wiremock/wiremock:3.10.0
    container_name: establishment
    volumes:
      - .wiremock/establishment/__files:/home/wiremock/__files
      - .wiremock/establishment/mappings:/home/wiremock/mappings
    ports:
      - 8083:8080

